minor: update babel deps in lockfile
Without this, received error `No "exports" main resolved in ...`

According to [this issue](https://github.com/babel/babel/issues/11216#issuecomment-595400322),
it is just the result of an incompatibility between a node version and a
babel version which can be worked around either by upgrading node or by
grabbing more recent versions of babel dependencies.

It may be perfectly sensible not to accept this PR as it relates to a
potentially outdated nodejs version.

```
$ yarn build
yarn run v1.22.5
$ run-p build:*
$ tsdx build
$ tsc && rollup -c rollup.config.js
✓ Creating entry file 4.1 secs
(babel plugin) Error: No "exports" main resolved in /Users/andrew.macleay/src/restful-react/node_modules/@babel/helper-compilation-targets/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/andrew.macleay/src/restful-react/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/andrew.macleay/src/restful-react/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:project" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```